const gameSettings = {
    MINIMUM_LENGTH: 10,
    MAX_CENTIPEDES: 9,
    MAX_MUSHROOMS: 300,
    SCALE: 0.2,
    MOVE_TIME: 0.15,
    SPIDER_MOVE_TIME: 0.2,
    FLEA_MOVE_TIME: 0.12,
    Snail_MOVE_TIME: 0.3,
    UP_BOUNDARY: 1,
    DOWN_BOUNDARY: 15,
    LEFT_BOUNDARY: 1,
    RIGHT_BOUNDARY: 15,

    SPIDER_CHANCE: 200,
    FLEA_CHANCE: 260,
    SNAIL_CHANCE: 380,
    MUSHROOM_CHANCE_NON_PLAYER: 32,
    MUSHROOM_CHANCE_PLAYER: 56,

    TRANSITION_TIME: 2.5,
    SHOOT_DELAY: 0.3,

    MIN_MUSHROOMS_BEFORE_FLEA: 60,
    SNAIL_POISON_DISTANCE: 0.4
}
export default gameSettings
